// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Webapp;

#nullable disable

namespace Webapp.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("Webapp.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Images")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("productDetail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Images = "D:\\Pyt\\Webapp\\Webapp\\assets\\battlecreek1",
                            Price = 199.0,
                            ProductName = "Battlecreek Coffee",
                            Timestamp = "06/02/2022",
                            productDetail = "กาแฟนำเข้าจากอเมริกา รสชาติกลมกล่อม"
                        },
                        new
                        {
                            Id = 2,
                            Images = "D:\\Pyt\\Webapp\\Webapp\\assets\\eniko",
                            Price = 1969.0,
                            ProductName = "eniko",
                            Timestamp = "06/02/2022",
                            productDetail = "กล้องฟิล์มหายาก"
                        },
                        new
                        {
                            Id = 3,
                            Images = "D:\\Pyt\\Webapp\\Webapp\\assets\\galina",
                            Price = 320.0,
                            ProductName = "galina",
                            Timestamp = "06/02/2022",
                            productDetail = "กระถางต้นไม้สวยๆ ไว้ประดับบ้าน"
                        },
                        new
                        {
                            Id = 4,
                            Images = "D:\\Pyt\\Webapp\\Webapp\\assets\\jakob",
                            Price = 670.0,
                            ProductName = "jakob",
                            Timestamp = "06/02/2022",
                            productDetail = "กระเป๋าหนังแท้รุ่น Limited"
                        });
                });

            modelBuilder.Entity("Webapp.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Email = "admin@gmail.com",
                            Name = "Admin",
                            Password = "admin",
                            UserName = "admin"
                        },
                        new
                        {
                            id = 2,
                            Email = "ratchanon0123@gmail.com",
                            Name = "รัชชานนท์ ถูกนึก",
                            Password = "1234",
                            UserName = "volt"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
